@baseUrl = http://localhost:5000/api/users

@contentType = application/json

#@email = "geo1@mail.com"
@email = "geomar99988.bastiani@gmail.com"
@password = "pwd12345"
@name = "Geomar Tomás Cadore Bastiani"

###
POST {{ baseUrl }}
Content-Type: {{ contentType }}
origin: {{ baseURL }}

{
  "name": {{ name }},
  "password": {{ password }},
  "email": {{ email }},
  "password": {{ password }},
  "role":"user"
}

###
PUT {{ baseUrl }}/32
Content-Type: {{ contentType }}
origin: {{ baseURL }}

{
  "password": "geo12345",
  "role": "adm"
}

###
PATCH  {{ baseUrl }}/21
Content-Type: {{ contentType }}
origin: {{ baseURL }}

{
  "password": {{ password }},
  "newPassword": "12345678"
}

###
DELETE {{ baseUrl }}/21
Content-Type: {{ contentType }}
origin: {{ baseURL }}


###
GET {{ baseUrl }}/

###
GET {{ baseUrl }}/me

###
PUT {{ baseUrl }}/me
Content-Type: {{ contentType }}
origin: {{ baseURL }}

{
  "name": "ggqgx"
}

### 
PATCH  {{ baseUrl }}/me/password
Content-Type: {{ contentType }}
origin: {{ baseURL }}

{
  "password": "geo12345",
  "newPassword":"12345678"
}

###
GET {{ baseUrl }}/8
